---
- id: ruff-lint-diff
  # https://github.com/astral-sh/ruff-pre-commit
  name: ruff-lint-diff
  description: "Show diff of ruff for linting"
  entry: ruff check --diff --force-exclude
  language: system
  types_or:
    - python
    - pyi
    - cython
    - jupyter
  minimum_pre_commit_version: "2.9.2"
  verbose: true
  require_serial: true
- id: ruff-lint
  # https://github.com/astral-sh/ruff-pre-commit
  name: ruff-lint
  description: "Fix by ruff for linting"
  entry: ruff check --fix --force-exclude
  language: system
  types_or:
    - python
    - pyi
    - cython
    - jupyter
  minimum_pre_commit_version: "2.9.2"
  require_serial: true
- id: ruff-format-diff
  # https://github.com/astral-sh/ruff-pre-commit
  name: ruff-format-diff
  description: "Show diff of ruff for formatting"
  entry: ruff format --diff --force-exclude
  language: system
  types_or:
    - python
    - pyi
    - cython
    - jupyter
  minimum_pre_commit_version: "2.9.2"
  verbose: true
  require_serial: true
- id: ruff-format
  # https://github.com/astral-sh/ruff-pre-commit
  name: ruff-format
  description: "Fix by ruff for formatting"
  entry: ruff format --force-exclude
  language: system
  types_or:
    - python
    - pyi
    - cython
    - jupyter
  minimum_pre_commit_version: "2.9.2"
  require_serial: true
- id: black-diff
  # https://github.com/psf/black
  name: black-diff
  description: Just show the diff of black result.
  entry: black
  language: system
  types_or:
    - python
    - pyi
    - cython
    - jupyter
  args:
    - "--diff"
    - "--color"
    - "--quiet"
  verbose: true
  require_serial: true
- id: black
  # https://github.com/psf/black
  name: black
  description: "Black: The uncompromising Python code formatter."
  entry: black
  language: system
  types_or:
    - python
    - pyi
    - cython
    - jupyter
  args:
    - "--quiet"
  require_serial: true
- id: blacken-docs
  # https://github.com/asottile/blacken-docs
  name: blacken-docs
  description: Run `black` on python code blocks in documentation files.
  entry: blacken-docs
  language: system
  files: '\.(rst|md|markdown|py|tex)$'
  require_serial: true
- id: autoflake-diff
  # https://github.com/PyCQA/autoflake
  name: autoflake-diff
  description: Just show the diff of autoflake result.
  entry: autoflake
  language: system
  types:
    - python
    - pyi
    - cython
    - jupyter
  verbose: true
  require_serial: true
- id: autoflake
  # https://github.com/PyCQA/autoflake
  name: autoflake
  description: autoflake removes unused imports and unused variables from Python code
  entry: autoflake
  language: system
  types:
    - python
    - pyi
    - cython
    - jupyter
  args:
    - "--in-place"
  require_serial: true
- id: autopep8-diff
  # https://github.com/pre-commit/mirrors-autopep8
  name: autopep8-diff
  description: Just show the diff of autopep8 result.
  entry: autopep8
  language: system
  types:
    - python
    - pyi
    - cython
    - jupyter
  args:
  - "--diff"
  require_serial: true
- id: autopep8
  # https://github.com/pre-commit/mirrors-autopep8
  name: autopep8
  description: autopep8 automatically formats Python code to conform to the PEP 8 style guide.
  entry: autopep8
  language: system
  types:
    - python
    - pyi
    - cython
    - jupyter
  args:
  - "--in-place"
  require_serial: true
- id: isort-diff
  # https://github.com/PyCQA/isort
  name: isort-diff
  description: Just show the diff of isort result.
  entry: isort
  language: system
  types_or:
    - python
    - pyi
    - cython
    - jupyter
  args:
    - '--diff'
    - '--filter-files'
  verbose: true
  require_serial: true
- id: isort
  # https://github.com/PyCQA/isort
  name: isort
  description: isort your imports, so you don't have to.
  entry: isort
  language: system
  types_or:
    - python
    - pyi
    - cython
    - jupyter
  args:
  - '--filter-files'
  require_serial: true
- id: flake8
  # https://github.com/PyCQA/flake8
  name: flake8
  description: "`flake8` is a command-line utility for enforcing style consistency across Python projects."
  entry: flake8
  language: system
  types:
    - python
    - pyi
    - cython
    - jupyter
  require_serial: true
- id: bandit
  # https://github.com/PyCQA/bandit
  name: bandit
  description: Bandit is a tool for finding common security issues in Python code
  entry: bandit
  language: system
  types:
    - python
    - pyi
    - cython
    - jupyter
  args:
  - "-c"
  - "pyproject.toml"
  require_serial: true
- id: mypy
  # https://github.com/pre-commit/mirrors-mypy
  name: mypy
  entry: mypy
  description: Mypy is a static type checker for Python.
  language: system
  types_or:
    - python
    - pyi
    - cython
    - jupyter
  pass_filenames: false
  require_serial: true
- id: numpydoc-validation
  # https://github.com/numpy/numpydoc
  name: numpydoc-validation
  entry: numpydoc lint
  description: This hook validates that docstrings in committed files adhere to numpydoc standards.
  language: system
  types:
    - python
    - pyi
    - cython
    - jupyter
  require_serial: true
- id: shellcheck
  # https://github.com/shellcheck-py/shellcheck-py
  name: shellcheck
  entry: shellcheck
  description: Test shell scripts with shellcheck.
  language: system
  types: [shell]
  require_serial: true
- id: mdformat-check
  # https://github.com/executablebooks/mdformat
  name: mdformat-check
  description: Just show the diff of mdformat result.
  entry: mdformat
  language: system
  types: [markdown]
  args:
    - "--check"
  require_serial: true
- id: mdformat
  # https://github.com/executablebooks/mdformat
  name: mdformat
  description: CommonMark compliant Markdown formatter
  entry: mdformat
  language: system
  types: [markdown]
  require_serial: true
- id: validate-pyproject
  # https://github.com/abravalheri/validate-pyproject
  name: validate-pyproject
  description: Validate pyproject.toml file
  entry: validate-pyproject
  language: system
  files: ^pyproject.toml$
  require_serial: true
